version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
     - POSTGRES_DB=gophkeeper
     - POSTGRES_USER=test
     - POSTGRES_PASSWORD=test
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8088:8080"


  gophkeeper-server:
    build:
      context: ../
      dockerfile: ./deployments/server/Dockerfile
    restart: always
    ports:
      - "3001:3001"

  client-builder:
      build:
        context: ../
        dockerfile: ./deployments/client/Dockerfile
      volumes:
        - ../bin:/app/bin
      privileged: true
#      entrypoint: ["tail", "-f", "/dev/null"]
      entrypoint: ["sh", "/app/deployments/client/build.sh"]
