BEGIN;
CREATE TABLE IF NOT EXISTS users
(
    id         SERIAL PRIMARY KEY,
    login      VARCHAR UNIQUE NOT NULL,
    password   VARCHAR        NOT NULL,
    created_at TIMESTAMPTZ    NOT NULL DEFAULT NOW()
);
COMMIT;