definitions:
  models.DefaultErrorResponse:
    properties:
      error:
        type: string
    type: object
  models.LoginRequest:
    properties:
      login:
        type: string
      password:
        type: string
    type: object
  models.LoginResponse:
    properties:
      crt:
        type: string
      token:
        type: string
    type: object
  models.Note:
    properties:
      created_at:
        type: string
      data:
        items:
          type: integer
        type: array
      data_type:
        type: string
      id:
        type: integer
      metadata:
        type: string
      updated_at:
        type: string
      userId:
        type: integer
    type: object
  models.User:
    properties:
      created_at:
        type: string
      login:
        type: string
      password:
        type: string
      user_id:
        type: integer
    type: object
info:
  contact: {}
paths:
  /notes:
    get:
      consumes:
      - application/json
      description: get user all notes
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: json
        "204":
          description: No Content
      summary: get all notes
      tags:
      - notes
  /notes/:noteID:
    get:
      consumes:
      - application/json
      description: get user note
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Note'
        "204":
          description: No Content
      summary: get note
      tags:
      - notes
  /notes/create:
    post:
      consumes:
      - application/json
      description: create user note
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Note'
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.DefaultErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/models.DefaultErrorResponse'
      summary: create note
      tags:
      - notes
  /user/login:
    post:
      consumes:
      - application/json
      description: user login
      parameters:
      - description: login
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/models.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.LoginResponse'
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Error
      summary: login
      tags:
      - auth
  /user/register:
    post:
      consumes:
      - application/json
      description: user registration
      parameters:
      - description: user account
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/models.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.DefaultErrorResponse'
        "404":
          description: Not Found
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/models.DefaultErrorResponse'
        "500":
          description: Internal Server Error
      summary: register
      tags:
      - auth
swagger: "2.0"
